create database Sales;
use Sales;

-- 1.WAQTD list all customers from a specific city.
select * from customers
where city='chennai';	

-- 2.WAQTD count the total number of customers.
select count(*) as 'Total num of customers'
from customers;

-- 3.WAQTD display all orders placed in a given year.
select* from orders
where order_date= 2023;

-- 4.WAQTD find the total number of orders.
select count(*) as "Total num of orders"
from orders;

-- 5.WAQTD find the total revenue generated from all orders.
select sum(unit_price) AS 'Total revenue'
from oi;

-- 6.WAQTD list all products with price greater than a given amount.
select * from products
where price>500;

-- 7.WAQTD find the minimum, maximum, and average product price.
select min(price) as 'Min price',
max(price) as 'Max price',
avg(price) as 'Avg price'
from products;

-- 8.WAQTD count how many products belong to each category.
select category, count(*) as 'Num of products'
from products
group by category;

-- 9.WAQTD list all orders with order status = ‘Completed’.
select * from orders
where order_status ='completed';

-- 10.WAQTD find the total quantity sold for each product.
select product_id, sum(quantity) as 'Num of product'
from oi
group by product_id;

-- 11.WAQTD find total sales amount per order.
select order_id, sum(unit_price) as 'Amount'
from oi
group by order_id;

-- 12.WAQTD display total revenue generated by each product.
select product_id, sum(unit_price) as 'Amount'
from oi
group by product_id;

-- 13.WAQTD find the total number of orders placed by each customer.
select customer_id, count(order_id) as 'Total num of products'
from orders
group by customer_id;

-- 14.WAQTD list customers who placed more than 5 orders.
select customer_id, count(order_id) as Totalorders
from orders
group by customer_id
order by Totalorders desc;

-- 15.WAQTD display total revenue generated by each customer.
select orders.customer_id, sum(oi.unit_price) as Totalrevenue
from orders
join oi on orders.order_id = oi.order_id
group by orders.customer_id;

-- 16.WAQTD find the top 5 highest selling products by revenue.
select product_id, sum(unit_price) as Revenue
from oi
group by product_id
order by Revenue desc
limit 5;

-- 17.WAQTD list all customers who have never placed an order.
select customers.*
from customers
left join orders on customers.customer_id = orders.customer_id
where orders.order_id is null;

-- 18.WAQTD find monthly total sales.
select year(orders.order_date) as 'Year', month(orders.order_date) as 'Month', sum(oi.quantity) as 'Total sales'
from orders
join oi ON orders.order_id = oi.order_id
group by year(orders.order_date), month(orders.order_date);

-- 19.WAQTD find average order value (AOV).
select avg(unit_price) as 'Avg order value'
from oi;

-- 20.WAQTD display category-wise total revenue.
select products.category, sum(oi.unit_price) as Revenue
from oi
join products on oi.product_id = products.product_id
group by products.category;

-- 21.WAQTD find products whose price is above the average product price.
select *
from products
where price >(
select avg(price) 
from products);

-- 22.WAQTD find the order with the highest total value.
select order_id, sum(unit_price) as 'Order total'
from oi
group by order_id
order by 'Order total' desc
limit 1;

-- 23.WAQTD find customers who placed orders in more than one month.
select customer_id
from orders 
group by customer_id
having count(month(order_date)) > 1;

-- 24.WAQTD list products that have never been sold.
select products.*
from products
left join oi on products.product_id = oi.product_id
where oi.product_id is null;

-- 25.WAQTD compare actual sales vs target sales for each month.
select month(orders.order_date) as Month, sum(oi.unit_price) as 'Actual sales', st.target_amount
from orders
join oi on orders.order_id = oi.order_id
join st on month(orders.order_date) = st.month
group by month(orders.order_date), st.target_amount;
